/**
 * Human-facing sitemap groups. Route details remain in the sitemap route's
 * existing catalog so its visible descriptions and JSON-LD stay unchanged.
 */
export const SITEMAP_GROUPS = Object.freeze([
  {
    title: "Timers",
    description: "General countdowns, presets, intervals, event timers, and the original multi-tool page.",
    routes: [
      "/",
      "/free-online-timers",
      "/countdown-timer",
      "/online-timer",
      "/fullscreen-timer",
      "/silent-timer",
      "/visual-timer",
      "/multiple-timers",
      "/interval-timer",
      "/seconds-timer",
      "/1-minute-timer",
      "/5-minute-timer",
      "/10-minute-timer",
      "/15-minute-timer",
      "/30-minute-timer",
      "/event-countdown",
      "/countdown-to-date",
      "/new-year-countdown",
      "/christmas-countdown",
      "/birthday-countdown",
    ],
  },
  {
    title: "Stopwatches",
    description: "Elapsed-time, count-up, reaction, solve, run, and game-clock tools.",
    routes: [
      "/stopwatch",
      "/stopwatch-with-milliseconds",
      "/count-up-timer",
      "/binary-stopwatch",
      "/speedcubing-timer",
      "/speedrun-timer",
      "/reaction-time-test",
      "/chess-clock",
    ],
  },
  {
    title: "Study and focus",
    description: "Focus sessions, work-and-break cycles, study countdowns, and time-blocking tools.",
    routes: [
      "/pomodoro-timer",
      "/break-timer",
      "/study-timer",
      "/productivity-timer",
      "/focus-session-timer",
      "/time-blocking-clock",
    ],
  },
  {
    title: "Fitness timers",
    description: "Workout intervals, rounds, pacing, rest, breathing, meditation, and everyday wellbeing timers.",
    routes: [
      "/hiit-timer",
      "/workout-timer",
      "/rest-timer",
      "/tabata-timer",
      "/meditation-timer",
      "/breathing-timer",
      "/sleep-timer",
      "/stretch-timer",
      "/drink-water-reminder-timer",
      "/emom-timer",
      "/amrap-timer",
      "/round-timer",
      "/boxing-timer",
      "/pace-timer",
    ],
  },
  {
    title: "Kitchen timers",
    description: "General cooking timers and focused timers for tea, eggs, and pizza.",
    routes: [
      "/cooking-timer",
      "/kitchen-timer",
      "/tea-timer",
      "/egg-timer",
      "/pizza-timer",
    ],
  },
  {
    title: "Classroom, meeting, presentation, and lab",
    description: "Tools for lessons, exams, talks, meetings, agendas, presentations, and informal experiments.",
    routes: [
      "/presentation-timer",
      "/speech-timer",
      "/classroom-timer",
      "/meeting-timer",
      "/meeting-agenda-timer",
      "/exam-timer",
      "/meeting-count-up-timer",
      "/lab-timer",
    ],
  },
  {
    title: "Alarms and rhythm",
    description: "Clock-time and duration alarms plus tempo-measurement and metronome tools.",
    routes: [
      "/alarm-timer",
      "/online-alarm-clock",
      "/metronome",
      "/bpm-tapper",
    ],
  },
  {
    title: "Digital and local clocks",
    description: "Readable local-time displays from minimal clocks to large digital views.",
    routes: [
      "/current-local-time",
      "/digital-clock",
      "/big-digital-clock",
      "/clock-with-seconds",
      "/minimalist-clock",
    ],
  },
  {
    title: "Analog and fullscreen clocks",
    description: "Analog clock styles and fullscreen displays for rooms, screens, and presentations.",
    routes: [
      "/analog-clock",
      "/analog-clock-with-second-hand",
      "/full-screen-analog-clock",
      "/smooth-second-hand-clock",
      "/full-screen-clock",
    ],
  },
  {
    title: "Millisecond, UTC, Unix, and exact-style displays",
    description: "Device-based precision displays, current UTC and Unix values, millisecond tools, and timestamp conversion.",
    routes: [
      "/clock-with-milliseconds",
      "/world-clock-with-milliseconds",
      "/utc-clock",
      "/epoch-unix-time-clock",
      "/atomic-clock",
      "/milliseconds-converter",
      "/millisecond-timer",
      "/unix-timestamp-converter",
    ],
  },
  {
    title: "World time and time zones",
    description: "Compare current times, convert a specific time, or plan a meeting across zones.",
    routes: [
      "/world-clock",
      "/world-clock-with-seconds",
      "/time-zone-converter",
      "/time-zone-meeting-planner",
    ],
  },
  {
    title: "Military and 12/24-hour time",
    description: "Convert clock formats or view current 12-hour, 24-hour, and military-time displays.",
    routes: [
      "/military-time-clock",
      "/military-time-converter",
      "/24-hour-clock",
      "/12-hour-clock",
    ],
  },
  {
    title: "Date and time calculators",
    description: "Calculate date ranges, durations, weekdays, workdays, calendar weeks, and time intervals.",
    routes: [
      "/time-calculator",
      "/time-duration-calculator",
      "/date-duration-calculator",
      "/date-calculator",
      "/business-days-calculator",
      "/workdays-calculator",
      "/age-calculator",
      "/days-until-calculator",
      "/weekday-calculator",
      "/week-number-calculator",
      "/months-between-dates-calculator",
      "/weeks-between-dates-calculator",
      "/hours-until-calculator",
    ],
  },
  {
    title: "Work and time tracking",
    description: "Calculate one shift, daily punches, weekly totals, and billable time without implying payroll results.",
    routes: [
      "/billable-hours-clock",
      "/work-hours-calculator",
      "/time-card-calculator",
      "/weekly-timesheet-calculator",
      "/billable-hours-calculator",
    ],
  },
  {
    title: "Novelty and experimental tools",
    description: "Alternative clock displays, astronomical views, playful timers, and debt-estimate tools.",
    routes: [
      "/chaos-timer",
      "/video-game-challenge-timer",
      "/fibonacci-clock",
      "/sunrise-sunset-clock",
      "/debt-repayment-timer",
      "/morse-code-clock",
      "/debt-clock",
      "/golden-hour-clock",
      "/moon-phase-clock",
      "/astronomical-clock",
      "/swatch-internet-time-clock",
      "/binary-clock",
      "/hexadecimal-clock",
      "/roman-numeral-clock",
      "/retro-flip-clock",
    ],
  },
  {
    title: "Trust and site information",
    description: "Ownership, contact, methodology, policies, copyright, and site navigation.",
    routes: [
      "/about",
      "/author/suhas-sunder",
      "/contact",
      "/how-ilovetimers-is-made",
      "/copyright",
      "/privacy",
      "/terms",
      "/cookies",
      "/sitemap",
    ],
  },
]);
