export const designTokens = {
  colors: {
    pageBackground: "var(--ilt-bg-page)",
    utilitySurface: "var(--ilt-bg-utility)",
    contentBand: "var(--ilt-bg-content)",
    panelSurface: "var(--ilt-bg-panel)",
    inputSurface: "var(--ilt-bg-input)",
    subtleSurface: "var(--ilt-bg-subtle)",
    hoverSurface: "var(--ilt-bg-hover)",
    borderSubtle: "var(--ilt-border-subtle)",
    textPrimary: "var(--ilt-text-primary)",
    textSecondary: "var(--ilt-text-secondary)",
    textMuted: "var(--ilt-text-muted)",
    textInverted: "var(--ilt-text-inverted)",
    amberAccent: "var(--ilt-accent)",
    amberAccentHover: "var(--ilt-accent-hover)",
    amberSurface: "var(--ilt-accent-surface)",
    focusRing: "var(--ilt-focus-ring)",
  },
  shadows: {
    interactive: "var(--ilt-shadow-interactive)",
    interactiveHover: "var(--ilt-shadow-interactive-hover)",
  },
  radii: {
    control: "var(--ilt-radius-control)",
    card: "var(--ilt-radius-card)",
  },
  layout: {
    pageSidePadding: "var(--ilt-page-x)",
    displayMin: "var(--ilt-display-min)",
    displayLarge: "var(--ilt-display-large)",
    displayStageMin: "var(--ilt-display-stage-min)",
    seoBandMax: "var(--ilt-seo-band-max)",
    seoReadable: "var(--ilt-seo-readable)",
  },
} as const;

export const tokenClasses = {
  page: "bg-[var(--ilt-bg-page)] text-[var(--ilt-text-primary)]",
  utilitySurface: "bg-[var(--ilt-bg-utility)]",
  contentBand: "bg-[var(--ilt-bg-content)]",
  panelSurface: "bg-[var(--ilt-bg-panel)]",
  inputSurface: "bg-[var(--ilt-bg-input)]",
  subtleSurface: "bg-[var(--ilt-bg-subtle)]",
  textPrimary: "text-[var(--ilt-text-primary)]",
  textSecondary: "text-[var(--ilt-text-secondary)]",
  textMuted: "text-[var(--ilt-text-muted)]",
  accent: "text-[var(--ilt-accent)]",
  sidePadding: "ilt-side-padding",
  focusRing: "ilt-focus-ring",
  interactiveShadow: "ilt-control-shadow",
  displayType: "ilt-display-type",
  displayTypeLarge: "ilt-display-type-large",
  displayStage: "ilt-display-stage",
  surfaceCard: "ilt-surface-card",
  surfaceMuted: "ilt-surface-muted",
  surfaceAccent: "ilt-surface-accent",
  inlinePill: "ilt-inline-pill",
  keycap: "ilt-keycap",
  contentLabel: "ilt-content-label",
  contentStrong: "ilt-content-strong",
  helperText: "ilt-helper-text",
  inputControl: "ilt-input-control",
} as const;
